version: '3'

services:
  postgresql:
    image: postgres:15.4
    environment:
      POSTGRES_DB: graphql
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: